Description: >
    This is a Todo backend service
Parameters: 

    TargetGroupName:
        Description: An target group name that will be prefixed to resource names
        Type: String

    VPC:
        Description: The VPC that the ECS cluster is deployed to
        Type: AWS::EC2::VPC::Id
        
    Cluster:
        Description: Please provide the ECS Cluster ID that this service should run on
        Type: String

    DesiredCount: 
        Description: How many instances of this task should we run across our cluster?
        Type: Number
        Default: 2

    LoadBalancer:
        Description: The Application Load Balancer to register with
        Type: String

Resources:

    Service: 
        Type: AWS::ECS::Service
        Properties: 
            Cluster: !Ref Cluster
            DesiredCount: !Ref DesiredCount
            TaskDefinition: !Ref TaskDefinition
            DeploymentConfiguration:
                MaximumPercent: 200
                MinimumHealthyPercent: 50
            LoadBalancers: 
                - ContainerName: "todo-backend"
                  ContainerPort: 3001
                  TargetGroupArn: !Ref TargetGroup

    TaskDefinition:
        Type: AWS::ECS::TaskDefinition
        Properties:
            Family: todo-backend
            ContainerDefinitions:
                - Name: todo-backend
                  Essential: true
                  Image: gustavoapolinario/microservices-node-todo-backend
                  Memory: 256
                  Environment: 
                    - Name: PORT
                      Value: 3001
                  PortMappings:
                    - ContainerPort: 3001
                  LogConfiguration:
                    LogDriver: awslogs
                    Options:
                        awslogs-group: !Ref AWS::StackName
                        awslogs-region: !Ref AWS::Region

    CloudWatchLogsGroup:
        Type: AWS::Logs::LogGroup
        Properties: 
            LogGroupName: !Ref AWS::StackName
            RetentionInDays: 365


    LoadBalancerListener:
        Type: AWS::ElasticLoadBalancingV2::Listener
        Properties:
            LoadBalancerArn: !Ref LoadBalancer
            Port: 3001
            Protocol: TCP 
            DefaultActions: 
                - Type: forward
                  TargetGroupArn: !Ref TargetGroup

    TargetGroup:
        Type: AWS::ElasticLoadBalancingV2::TargetGroup
        Properties:
            Name: !Ref TargetGroupName
            VpcId: !Ref VPC
            Port: 3001
            Protocol: TCP

