Description: >
    This template deploys an Network Load Balancer that exposes our various ECS services.
    We create them it a seperate nested template, so it can be referenced by all of the other nested templates.
Parameters:

    EnvironmentName:
        Description: An environment name that will be prefixed to resource names
        Type: String


    VPC:
        Type: AWS::EC2::VPC::Id
        Description: Choose which VPC the Network Load Balancer should be deployed to

    Subnets:
        Description: Choose which subnets the Network Load Balancer should be deployed to
        Type: List<AWS::EC2::Subnet::Id>

    SecurityGroup:
        Description: Select the Security Group to apply to the Network Load Balancer
        Type: AWS::EC2::SecurityGroup::Id

Resources:

    LoadBalancer:
        Type: AWS::ElasticLoadBalancingV2::LoadBalancer
        Properties:
            Name: !Join [ "-", [ "NLB", !Ref EnvironmentName ]]
            Subnets: !Ref Subnets
            SecurityGroups: 
                - !Ref SecurityGroup
            Tags: 
                - Key: Name
                  Value: !Ref EnvironmentName
            Scheme: internal

           
Outputs:

    LoadBalancer:
        Description: A reference to the Network Load Balancer
        Value: !Ref LoadBalancer

    LoadBalancerDNS:
        Description: The URL of the ALB
        Value: !GetAtt LoadBalancer.DNSName
